services:
  database:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "SenhaRootSeguraAqui"
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
      MYSQL_PASSWORD: "SenhaDoBancoAqui"

  cache:
    image: redis:7-alpine
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:v1.11.11
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    volumes:
      - ./data/var/:/app/var/
      - ./data/nginx/:/etc/nginx/http.d/
      - ./data/certs/:/etc/ssl/certs/
    environment:
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      APP_URL: "http://IP_DA_SUA_VPS" # Altere para https:// seu domínio se usar SSL
      APP_TIMEZONE: "America/Sao_Paulo"
      DB_HOST: "database"
      DB_PORT: 3306
      DB_DATABASE: "panel"
      DB_USERNAME: "pterodactyl"
      DB_PASSWORD: "SenhaDoBancoAqui"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_CONNECTION: "redis"
      REDIS_HOST: "cache"
